services:
  db:
    image: postgres:16-alpine
    container_name: openbench-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openbench
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: openbench-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/openbench?sslmode=disable
      PORT: 3000


volumes:
  postgres_data:
