with-expecter: true
all: false
dir: "mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/denden-dr/openbench/apps/backend/internal/repository:
    config:
      dir: "mocks/repository"
      outpkg: "repository"
    interfaces:
      TicketRepository:
      WarrantyClaimRepository:
      Transaction:
  github.com/denden-dr/openbench/apps/backend/internal/service:
    config:
      dir: "mocks/service"
      outpkg: "service"
    interfaces:
      TicketService:
      WarrantyClaimService:
