ALTER TABLE claims DROP COLUMN IF EXISTS warranty_ticket_ref_id;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'RECEIVED';
ALTER TABLE claims ADD COLUMN IF NOT EXISTS repair_action TEXT;
